# Generated by Django 4.2.16 on 2024-11-21 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease_detector', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='detections',
            new_name='detection',
        ),
    ]
